Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  #config.vm.provision "shell", path: "script.sh"

  config.vm.define "Alura-challenge-app" do |app|
    app.vm.network "public_network"
    app.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
      v.name = "Alura-challenge"
    end
  end

###### Maquina Banco ######
  config.vm.define "Alura-challenge-bd" do |bd|
        bd.vm.network "public_network"
        bd.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
          v.name = "Alura-challenge-bd"
        end
  end

  
end
