Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  #config.vm.provision "shell", path: "script.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.name = "ubuntu20teste"
  end

  config.vm.define "ubuntu20teste" do |m|
	m.vm.network "public_network"
  end
  
end
