Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  #config.vm.provision "shell", path: "script.sh"

  ###### Maquina APP #####
  config.vm.define "moodle-app02" do |app|
        app.vm.network "public_network"
        app.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
          v.name = "moodle-app02"
        end
  end

end
