version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 8443:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
