Vagrant.configure("2") do |config|

  #config.vm.box = "centos/7"
  #config.vm.provision "shell", path: "script.sh"

  #---Configuração CentOS 79 -----
  config.vm.box = "bento/centos-7.9"
  config.vm.box_version = "202107.21.0"

  config.vm.provider "virtualbox" do |v|
     v.memory = 2048
     v.name = "centos7-9"
  end

  config.vm.define "centos7-9" do |m|
  	m.vm.network "public_network"
  end
  
end
