Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  #config.vm.provision "shell", path: "script.sh"

  #Configuração do servidor WEB (Apache + PHP)
  config.vm.define "lampweb" do |lampweb|
    lampweb.vm.network "public_network", ip: "192.168.100.190"
    lampweb.vm.provision "shell",
      inline: "sudo apt update &&\
               sudo apt install -y apache2 &&\
               sudo apt install -y ghostscript &&\
               sudo apt install -y libapache2-mod-php &&\
               sudo apt install -y php &&\
               sudo apt install -y php-bcmath &&\
               sudo apt install -y php-curl &&\
               sudo apt install -y php-imagick &&\
               sudo apt install -y php-intl &&\
               sudo apt install -y php-json &&\
               sudo apt install -y php-mbstring &&\
               sudo apt install -y php-mysql &&\
               sudo apt install -y php-xml &&\
               sudo apt install -y php-zip"

    #Configuração da VM
    lampweb.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "LAMP-WEB"
    end  
  end
  #Configuracao servidor de banco (MYSQL)
  config.vm.define "db01" do |db01|
    db01.vm.network "public_network", ip: "192.168.100.191"
    db01.vm.provision "shell",
      inline: "sudo apt update &&\ 
               sudo apt install mysql-server -y" 
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "DB01"
    end 

    # mysqlserver.vm.provision "shell",
      # inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"
  end  

end
